export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_ERRORS = 'GET_ERRORS';

export const GET_NEW_LEADS = 'GET_NEW_LEADS';
export const GET_CONTACT_LEADS = 'GET_CONTACT_LEADS';
export const GET_QUALIFIED_LEADS = 'GET_QUALIFIED_LEADS';